// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcrgsntiyxpubiosgerf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcmdzbnRpeXhwdWJpb3NnZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjU0MjQsImV4cCI6MjA3NzkwMTQyNH0.NEv82PTFty1mVpMh5hBqeWaka-dnhIb5rp7QBZ6dafc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});